@startuml
title Architecture (next, react)
skinparam componentStyle rectangle

component [API (22 files)] as API <<entryPoint>>
component [App (7 files)] as App
component [Features (10 files)] as Features
component [Graphplanner (45 files)] as Graphplanner
component [Hooks (9 files)] as Hooks
component [Lib (6 files)] as Lib
component [Other (9 files)] as Other
component [Repositoryworkspace (43 files)] as Repositoryworkspace
component [Server (10 files)] as Server

API --> App
API --> Features
API --> Graphplanner
API --> Hooks
API --> Lib
API --> Other
API --> Repositoryworkspace
API --> Server
App --> API
App --> Features
App --> Graphplanner
App --> Hooks
App --> Lib
App --> Other
App --> Repositoryworkspace
App --> Server
Graphplanner --> Features
Graphplanner --> Server
Hooks --> API
Hooks --> Features
Hooks --> Lib
Hooks --> Other
Hooks --> Repositoryworkspace
Other --> Graphplanner
Repositoryworkspace --> API
Repositoryworkspace --> Features
Repositoryworkspace --> Hooks
Repositoryworkspace --> Lib
Repositoryworkspace --> Server
Server --> Features
Server --> Lib
@enduml
